#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER supabase_admin WITH CREATEROLE CREATEDB REPLICATION BYPASSRLS PASSWORD '$POSTGRES_PASSWORD';
    CREATE USER authenticator WITH NOINHERIT CREATEROLE LOGIN PASSWORD '$POSTGRES_PASSWORD';
    CREATE USER supabase_auth_admin WITH NOINHERIT CREATEROLE LOGIN PASSWORD '$POSTGRES_PASSWORD';
    CREATE USER supabase_storage_admin WITH NOINHERIT CREATEROLE LOGIN PASSWORD '$POSTGRES_PASSWORD';
    
    CREATE SCHEMA IF NOT EXISTS _realtime;
    ALTER SCHEMA _realtime OWNER TO supabase_admin;

EOSQL
